#!/bin/bash
sudo apt update && sudo apt upgrade -y
apt install python3-pip -y
git clone https://github.com/ilya-work1/domain-monitoring-project.git
pip install -r domain-monitoring-project/requirements.txt --break-system-packages
cd domain-monitoring-project
python3 app.py
