#!/bin/bash

# Script to deploy the application using Docker and push image to Docker Hub

# Ensure the script is run as root
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run as root" >&2
  exit 1
fi

# Docker Hub credentials
DOCKER_USERNAME="razielrey"
DOCKER_REPOSITORY="domainmonitoring"
DOCKER_TAG="1.0.1"

# Update the system
echo "Updating system packages..."
apt update && apt upgrade -y

# Install Docker
echo "Installing Docker..."
apt install docker.io -y

# Enable & start Docker service
echo "Enabling and starting Docker service..."
systemctl enable docker
systemctl start docker

# Create application directory
echo "Setting up application directory..."
mkdir -p /root/domain-monitoring-docker
cd /root/domain-monitoring-docker

# Clone repository
echo "Cloning application repository..."
git clone https://github.com/ilya-work1/domain-monitoring-project.git .

# Build the Docker image using the existing dockerbuild file
echo "Building Docker image using existing dockerbuild file..."
docker build -t ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG} -f Dockerfile .

# Push the image to Docker Hub
echo "Logging in to Docker Hub..."
docker login -u "${DOCKER_USERNAME}"

echo "Pushing Docker image to Docker Hub..."
docker push ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}

# Run the Docker container
echo "Running Docker container..."
docker run -d --name domain-monitoring-container -p 8080:8080 ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:${DOCKER_TAG}

# Check running containers
docker ps

echo "Deployment completed with version ${DOCKER_TAG} and pushed to Docker Hub on port 8080!"
