#!/bin/bash
DOCKER_USERNAME=$1
DOCKER_PASSWORD=$2
sudo apt update && sudo apt -y install docker.io
echo "$DOCKER_PASSWORD" | sudo docker login --username $DOCKER_USERNAME --password-stdin
if [ $? -ne 0 ]; then
    echo "Docker login failed. Exiting..."
    exit 1
fi
echo "Login successful, continuing with script..."
sudo git clone https://github.com/ilya-work1/domain-monitoring-project.git
cd domain-monitoring-project/
sudo docker build -t ilyashev1/monitorsystem:1.0.0 .
sudo docker push ilyashev1/monitorsystem:1.0.0
